reasoning_options = [{ type = "effort", values = ["high", "max"] }]
base_model = "zhipuai/glm-5.2"
name = "GLM 5.2"

[interleaved]
field = "reasoning_content"

[cost]
input = 0.94
output = 2.9000000000000004
cache_read = 0.16999999999999998
cache_write = 0

[modalities]
input = ["text"]
output = ["text"]
