name = "Llama-3.1-Nemotron-Ultra-253B-v1"
base_model = "nvidia/llama-3.1-nemotron-ultra-253b"
attachment = false
reasoning = false
tool_call = true
structured_output = true
temperature = true
knowledge = "2024-12"
release_date = "2025-01-15"
last_updated = "2026-06-28"
open_weights = true

[cost]
input = 0.6
output = 1.8

[limit]
context = 128_000
input = 120_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]