base_model = "minimax/MiniMax-M3"
reasoning_options = [{ type = "toggle" }]

[cost]
input = 0.1373076
output = 0.5492304

[provider]
npm = "@ai-sdk/anthropic"
api = "https://zenmux.ai/api/anthropic/v1"
